language: node_js
node_js:
  - "node"
before_install:
  - rm .npmrc
script:
  - yarn run test
  - yarn run build
branches:
  only:
    - master
cache:
  yarn: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
